CREATE SCHEMA cc


--Table Creations
CREATE TABLE cc.Customer (
    [FirstName] NVARCHAR(150),
    [LastName] NVARCHAR(150),
    [CardNumber] INT NOT NULL,
    [CustomerID] INT NOT NULL PRIMARY KEY, 
)

CREATE TABLE cc.Product (
    [PName] NVARCHAR(150),
    [PPrice] DECIMAL(10,2),
    [ProductID] INT NOT NULL PRIMARY KEY, 
)

CREATE TABLE cc.Orders (
    [CustomerID] INT NOT NULL FOREIGN KEY REFERENCES cc.Customer (CustomerID),
    [ProductID] INT NOT NULL FOREIGN KEY REFERENCES cc.Pruduct (ProductID),
    [OrderID] INT NOT NULL PRIMARY KEY, 
)

-- Add 3 records to each table
INSERT INTO cc.Customer (FirstName, LastName, CardNumber, CustomerID) VALUES ("Anthony", "Harrington", 123, 001)
INSERT INTO cc.Customer (FirstName, LastName, CardNumber, CustomerID) VALUES ("Bob", "Harrington", 456, 002)
INSERT INTO cc.Customer (FirstName, LastName, CardNumber, CustomerID) VALUES ("John", "Harrington", 789, 003)

INSERT INTO cc.Product (PName, PPrice, ProductID) VALUES ("Balloon", 10.25, 001)
INSERT INTO cc.Product (PName, PPrice, ProductID) VALUES ("Stick", 1.99, 002)
INSERT INTO cc.Product (PName, PPrice, ProductID) VALUES ("Car", 100.99, 003)

-- Add Tina Smith into customer and iPhone to product
INSERT INTO cc.Product (PNAME, PPrice, ProductID) VALUES ("iPhone", 200.00, 004)
INSERT INTO cc.Customer (FirstName, LastName, CardNumber, CustomerID) VALUES ("Tina", "Smith", 555, 004)

-- Create order Tina Smith bought iPhone


-- Report all orders by Tina Smith
SELECT 

-- Report all revenue generated by sales of iPhone
SELECT (SUM())PPrice FROM cc.Orders WHERE ProductID = 004

-- increase price off iphone
Update cc.Product SET PPrice = 250.00 WHERE ProductID = 004